server:
  port: 8080
#langchain4j测试模型
#langchain4j:
#  open-ai:
#    chat-model:
#      api-key: demo
#      model-name: gpt-4o-mini
#      temperature: 0.7
#      base-url: http://langchain4j.dev/demo/openai/v1
#      #请求和响应日志
#      log-requests: true
#      log-responses: true
#启用日志debug级别
logging:
  level:
    root: info
langchain4j:
  open-ai:
    ## deep_seek
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: ${DEEP_SEEK_API_KEY}
#      model-name: deepseek-chat
#      temperature: 0.7
#      #请求和响应日志
#      log-requests: true
#      log-responses: true
      chat-model:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: deepseek-r1
        temperature: 0.7
        #请求和响应日志
        log-requests: true
        log-responses: true

  # ollama
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: qwen2.5:3b
      temperature: 0.7
      #请求和响应日志
      log-requests: true
      log-responses: true
  ## dash_scope_qwen
  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-plus
        parameters:
          temperature: 0.7
      streaming-chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-plus
        parameters:
          temperature: 0.7

  ## dash_scope_deepseek
#  community:
#    dashscope:
#      chat-model:
#        api-key: ${DASH_SCOPE_API_KEY}
#        model-name: deepseek-r1
#        parameters:
#          temperature: 0.7
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
  datasource:
    url: jdbc:mysql://localhost:3306/ai_chat_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# OpenAPI 3 基本配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html  # Swagger UI 路径
#    tags-sorter: alpha      # 按字母排序标签
#    operations-sorter: alpha # 按字母排序接口
#  api-docs:
#    path: /v3/api-docs      # OpenAPI 文档路径
#  group-configs:
#    - group: 'default'      # 默认分组
#      paths-to-match: '/**' # 匹配所有路径
#      packages-to-scan: com.li.controller # 扫描的 Controller 包
## Knife4j 增强配置
#knife4j:
#  enable: true             # 启用 Knife4j 增强功能
#  setting:
#    language: zh_cn        # 中文界面
#    enable-swagger-models: true # 显示模型
#    enable-footer: false   # 是否显示页脚

